# Generated by Django 3.2 on 2022-02-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
